config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :leagues
  resources :users
  resources :teams
  resources :stories
  resources :comments
  resources :rankings
  resources :topics

  # You can have the root of your site routed with "root"
  root to: "application#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/league.rb
class League
  include Mongoid::Document
  include Mongoid::Timestamps

  include Uploadable


  field :name, type: String
  field :image_url, type: String
  field :user_ids, type: Array, default: []
  field :admin_ids, type: Array, default: []
  field :creator_id, type: Moped::BSON::ObjectId
  field :team_ids, type: Array, default: []

  def self.with_user(user)
    where(:user_ids.in => [user.id])
  end

  def rankings
    Ranking.where(league_id: id).to_a
  end

  def creator
    User.find(creator_id)
  end

  def creator=(user)
    creator_id = user.id
  end

  def users
    User.for_league(self).to_a
  end

  def admins
    User.where(:id.in => admin_ids).to_a
  end

  def teams
    Team.where(:id.in => team_ids).to_a
  end

  def add_team(team)
    user_ids << team.owner_id
    team_ids << team.id
  end

  def add_team!(team)
    add_team(team)
    save
  end

  def admin?(user)
    admin_ids.include?(user.id)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < BaseController

  before_filter :get_league, only: [:show, :edit, :new, :update, :create]
  before_filter :get_associated, only: [:show, :edit]

  RESOURCE_NAME = :league
  WHITELISTED_PARAMS = [:name]
  PROCESS_ASSETS = true

  def index
    @leagues = League.limit(100).to_a

    league_ids = @leagues.map(&:id)
    @teams = Team.where(:league_id.in => league_ids).to_a
  end

  def show
    @stories = Story.for_parent(@league).order_by(:created_at.desc).to_a
    @topics = Topic.for_parent(@league).order_by(:updated_at.desc).to_a
  end

  def edit

  end

  def update
    redirect_to root_path unless @league.admin?(current_user)

    update_resource

    redirect_to league_path(@league)
  end

  def new

  end

  def create
    update_resource

    redirect_to league_path(@league)
  end

  private

  def get_league
    if params[:id]
      @league ||= League.find(params[:id])
    end

    @league ||= new_league
  end

  def new_league
    League.new(creator_id: current_user.id, admin_ids: [current_user.id], user_ids: [current_user.id])
  end

  def get_associated
    @users ||= @league.users
    @admins ||= @users.select{|u| @league.admin?(u)}
    @teams ||= @league.teams
    @rankings ||= @league.rankings
    @users_by_team_id ||= get_users_by_team_id
  end

end

app/views/leagues/_stories_feed.haml
- first_story = true
- for story in stories
  .row{ style: 'margin-bottom: 1em'}
    - if first_story
      - first_story = false
      .col-lg-12
        - if story.has_uploads?
          = link_to story_path(story) do
            %p.img-preview.img-rounded
              = image_tag story.upload_url, class: 'img-rounded img-responsive'

        %p{style: 'margin-top: 0.5em'}
          = link_to story.title, story_path(story), class: 'h3'

        %p= link_to truncate(story.body, length: 140), story_path(story)

    - else
      - if story.has_uploads?
        .col-lg-6
          = link_to story_path(story), class: 'h4' do
            %p.img-preview.small.img-rounded
              = image_tag story.upload_url, class: 'img-rounded img-responsive'
        .col-lg-6
          = link_to story.title, story_path(story), class: 'h4'

      - else
        .col-lg-12
          = link_to story.title, story_path(story), class: 'h4'

app/views/leagues/edit.haml
= link_to "Back to League", league_path(@league), class: 'btn-xs btn-default btn'

= form_for @league, html: { class: 'form-horizontal' } do |f|
  .form-group
    %label.col-sm-2.control-label Name

    .col-sm-10
      = f.text_field :name, class: 'form-control', placeholder: 'Name'

  .form-group
    %label.col-sm-2.control-label Admins

    .col-sm-10
      - for admin in @admins
        = link_to admin.name, user_path(admin)

  .form-group
    %label.col-sm-2.control-label Teams

    .col-sm-10
      - for team in @teams
        - user = @users_by_team_id[team.id]
        = link_to team.name, team_path(team)
        %span owner:
        = link_to user.name, user_path(user)

  .form-group
    %label.col-sm-2.control-label Logo

    .col-sm-10
      =f.file_field :asset

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Save", class: 'btn btn-primary'

app/views/leagues/index.haml
- content_for(:header, "Joining A League")

.col-lg-6.col-lg-offset-3
  - for league in @leagues
    - teams = @teams.select{|t| t.league_id == league.id}
    - has_team_in_league = teams.any?{|t| t.owner_id == current_user.id}
    - is_admin_of_league = league.admin?(current_user)

    %p{style: 'margin-bottom: 2em'}
      - if has_team_in_league
        = link_to league.name, league_path(league)
        %span (you belong to this league)
      - else
        %span= league.name
        = link_to "Join", new_team_path(team: { owner_id: current_user.id, league_id: league.id }), class: 'btn btn-md btn-primary'

      - if is_admin_of_league
        %span (you're an admin of this league)

app/views/leagues/new.html.haml
- content_for(:header, "New League")

.row
  = form_for @league, html: { class: 'form-horizontal' } do |f|
    .form-group
      .col-lg-offset-2.col-lg-1 Name

      .col-lg-6= f.text_field :name

    .form-group
      .col-lg-offset-2.col-lg-1 Pic

      .col-lg-6=f.file_field :asset

    .form-group
      .col-sm-offset-3.col-sm-10
        = f.submit nil, class: 'btn btn-default'

app/views/leagues/show.haml
- content_for(:header, "#{@league.name} Home")

.row
  .col-lg-4
    - if @league.admin?(current_user)
      %p= link_to "New Story", new_story_path(story: {parent_id: @league.id, parent_type: "League"}), class: 'btn btn-success btn-sm'

      %p= link_to "New Ranking", new_ranking_path(ranking: {league_id: @league.id}), class: 'btn btn-primary btn-sm'

      %p= link_to 'Edit League', edit_league_path(@league), class: 'btn btn-default btn-sm'

    - if @stories.present?
      %h3 Stories
      = render partial: 'stories_feed', locals: { stories: @stories }

  .col-lg-8
    - has_team_in_league = @teams.any?{|t| t.owner_id == current_user.id}
    - if !has_team_in_league
      %p
        %strong You don't yet have a team in this league
      %p= link_to "Create a team", new_team_path(team: { owner_id: current_user.id, league_id: @league.id }), class: 'btn btn-primary btn-sm'

    - else
      - if @rankings.present?
        - ranking = @rankings.last
        %p
          %span.h3 Current Power Rankings
          = link_to("(view)", ranking_path(ranking))
        = render partial: 'rankings/ranking', locals: { ranking: ranking, preview: true }

      %h3 Threads
      %p= link_to "New Thread", new_topic_path(topic: {parent_id: @league.id, parent_type: "League"}), class: 'btn btn-info btn-sm'

      - if @topics
        - for thread in @topics
          %p= link_to thread.name, topic_path(thread)
      - else
        %p (No Threads Yet.)