config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :leagues
  resources :users
  resources :teams
  resources :stories
  resources :comments
  resources :rankings
  resources :topics

  # You can have the root of your site routed with "root"
  root to: "application#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/topic.rb
class Topic
  include Postable
  include Uploadable

  def children
    Comment.for_parent(self).to_a
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < BaseController

  before_filter :find_topic, only: [:new, :show, :create, :edit, :update]
  before_filter :get_associated, only: [:show, :edit, :update, :create]

  RESOURCE_NAME = :topic
  WHITELISTED_PARAMS = [:title, :body, :parent_id, :parent_type]
  PROCESS_ASSETS = true

  def new

  end

  def create
    update_resource

    redirect_to topic_path(@topic)
  end

  def update
    update_resource

    redirect_to topic_path(@topic)
  end

  def show
    @comments = @topic.children

    if @comments.present?
      comment_creator_ids = @comments.map(&:creator_id)
      @users = User.where(:id.in => comment_creator_ids).to_a
    end
  end

  def edit

  end

  private

  def find_topic
    if params[:id]
      @topic ||= Topic.find(params[:id])
    end

    @topic ||= new_topic
  end

  def get_associated
    @parent ||= @topic.parent
    @creator ||= @topic.creator
  end

  def new_topic
    atts = mass_assignable_atts
    atts[:creator_id] = current_user.id

    Topic.new(atts)
  end

end

app/views/topics/new.haml
- content_for(:header, "New Topic")

= form_for @topic, html: { class: 'form-horizontal' } do |f|
  = f.hidden_field :parent_id
  = f.hidden_field :parent_type
  = f.hidden_field :creator_id

  .form-group
    %label.col-sm-2.control-label Title

    .col-sm-10
      = f.text_field :title, class: 'form-control', placeholder: 'Title'

  .form-group
    %label.col-sm-2.control-label Body

    .col-sm-10
      = f.text_area :body, class: 'form-control', placeholder: 'Body'

  .form-group
    %label.col-sm-2.control-label Pic

    .col-sm-10
      =f.file_field :asset


  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "New Thread", class: 'btn btn-default'

app/views/topics/show.haml
- content_for(:header, @topic.title)

- if @parent.is_a?(League)
  = link_to "Back to League", league_path(@parent), class: 'btn-xs btn-default btn', style: 'margin-bottom: 2em'

.row
  .col-lg-4
    - if @topic.has_uploads?
      = image_tag @topic.upload_url, class: 'img-rounded img-responsive'

    %p{ style: 'margin-top: 1em'}
      %span Posted in
      = link_to @parent.name, polymorphic_path(@parent)

      %span by
      = link_to @creator.name, user_path(@creator)

  .col-lg-8
    = @topic.body

    %p{style: 'margin-top: 2em'}
      = link_to "Add a Reply", new_comment_path(comment: { parent_id: @topic.id, parent_type: "Topic" }), class: 'btn btn-primary btn-sml'

    - if @comments.present?
      .container
        .row{style: 'margin-top: 2em'}
          %h4= pluralize(@comments.count, "Reply")

          - for comment in @comments
            - comment_creator = @users.detect{ |u| u.id == comment.creator_id }
            %hr
            = render partial: "shared/comment_stub", locals: { comment: comment, user: comment_creator }