config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :leagues
  resources :users
  resources :teams
  resources :stories
  resources :comments
  resources :rankings
  resources :topics

  # You can have the root of your site routed with "root"
  root to: "application#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @leagues = League.with_user(current_user) if current_user

    if @leagues && @leagues.count == 1 # I'm ok with this for now but yeah it kinda sucks
      redirect_to league_path(@leagues.first)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.haml
%nav.navbar.navbar-inverse.navbar-static-top{ role: 'navigation'}
  .container-fluid
    .navbar-header
      = link_to "fooball", root_path, class: 'navbar-brand'

    %ul.nav.navbar-nav

    %ul.nav.navbar-nav.navbar-right
      - if current_user
        %li= link_to 'Your Profile', user_url(current_user)
        %li= link_to 'Sign Out', logout_path
      - else
        %li
          = link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2)

app/views/application/index.haml
- if current_user
  - if @leagues.present?
    .row
      %p Leagues you're in:
      - for league in @leagues
        %div
          = link_to league.name, league_path(league)

  .row{style: 'margin-top: 2em;'}
    - if League.present?
      %p= link_to "Join a League", leagues_path, class: 'btn btn-primary'
    - else
      %p Ok, so there aren't any leagues, so you should probably create one:
  .row
    = link_to 'New League', new_league_path, class: 'btn btn-default btn-sm'

- else
  .jumbotron.col-md-6.col-md-offset-3.text-center
    %h3="You're not signed in."

    = link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), class: "btn btn-lg btn-success"